#!/bin/bash

set -ex

source $(dirname "$0")/version-util.sh

CGO_ENABLED=0 GOOS=linux go build -mod=vendor -ldflags="-X 'main.Version=$(get_kappctrl_ver)+develop'" -trimpath -o controller-linux-amd64 ./cmd/controller/...

echo "# -- this file is autogenerated by dev-deploy.sh from main Dockerfile and is not version controlled" > Dockerfile.dev

run_image_start=`cat Dockerfile | grep -n "\- run image \-" | cut -d':' -f1`
tail -n +$run_image_start Dockerfile | \
  sed 's/COPY --from=deps.*/COPY controller-linux-amd64 kapp-controller/' >> Dockerfile.dev

ytt -f config/package-bundle/config -f config/dev -v dev.version="$(get_kappctrl_ver)+develop" --data-value-yaml dev.rapid_deploy=true | kbld -f- | kapp deploy -a kc -f- -c -y
